dist: bionic
language: java
jdk:
  - openjdk8
  - openjdk11

before_install:
 - chmod +x gradlew
 - git config --unset-all remote.origin.fetch
 - git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
 - git fetch --unshallow
 - git fetch origin testbranch:testbranch

install: 
- gradle wrapper

after_failure:
- cat build/test-results/test/*.xml
